apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-villa-deployment
  labels:
    app: new-villa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-villa
  template:
    metadata:
      labels:
        app: new-villa
    spec:
      containers:
      - name: new-villa-container
        image: arishwaran/new-villa:latest
        ports:
        - containerPort: 80
