apiVersion: v1
kind: Service
metadata:
  name: new-villa-service
  labels:
    app: new-villa
spec:
  type: LoadBalancer
  selector:
    app: new-villa
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the LoadBalancer
      targetPort: 80  # Port your container is listening on
